name: daq
channels:
  - conda-forge
dependencies:
  - erlab>=2.4.2
  - h5netcdf
  - humanize
  - matplotlib-base
  - numbagg
  - numpy
  - opencv-python
  - pandas
  - pip
  - pre-commit
  - pymodbus
  - pyqtgraph>=0.13.4
  - python=3.11
  - pyvisa
  - pywin32
  - pywinauto
  - pyzmq
  - qtawesome>=1.3.1
  - qtpy
  - slack_sdk
  - tomlkit
  - xarray
  - pip:
    - pypylon
    - pyqt6
