name: Build F70H Helium Compressor Monitor

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:

  build:
    name: Build F70H Helium Compressor Monitor
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install

    - name: Install the project
      working-directory: ./src/f70h
      run: uv sync --all-extras --dev

    # - name: Install UPX
    #   uses: crazy-max/ghaction-upx@v2
    #   with:
    #     install-only: true

    - name: Building...
      working-directory: ./src/logviewer
      run: uv run pyinstaller main.spec

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: F70H Monitor
        path: src/f70h/dist/f70h/
