name: Build Log Viewer (MacOS)

on:
  workflow_dispatch:

jobs:

  build:
    name: Build Log Viewer
    runs-on: macos-14
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Resolving dependencies...
      run: pip install -r src/logviewer/requirements.txt pyinstaller

    - name: Building...
      run: pyinstaller src/logviewer/main.spec

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Log Viewer
        path: dist/