name: Build MG15 Vacuum Gauge Logger

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:

  build:
    name: Build MG15 Vacuum Gauge Logger
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install

    - name: Install the project
      working-directory: ./src/mg15
      run: uv sync --all-extras --dev

    - name: Building...
      working-directory: ./src/mg15
      run: uv run pyinstaller main.spec

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: MG15
        path: src/mg15/dist/mg15/
