name: Build Basler Camera Monitor

on:
  workflow_dispatch:

jobs:

  build:
    name: Build Basler Camera Monitor
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install UPX
      uses: crazy-max/ghaction-upx@v2
      with:
        install-only: true

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Resolving dependencies...
      run: pip install -r requirements_basler.txt pyinstaller

    - name: Building...
      run: pyinstaller framegui.spec

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: Camera Monitor
        path: dist/framegui/