name: Build Log Viewer (MacOS)

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:

  build:
    name: Build Log Viewer
    runs-on: macos-15
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: Create venv
      working-directory: ./src/logviewer
      run: |
        python -m venv .venv

    - name: Install the project
      working-directory: ./src/logviewer
      run: |
        source .venv/bin/activate
        pip install pyinstaller .

    - name: Building...
      working-directory: ./src/logviewer
      run: |
        source .venv/bin/activate
        pyinstaller main.spec

    - name: Create archive with symlinks
      run: tar -czhf artifact.tar.gz ./src/logviewer/dist/logviewer/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Log Viewer
        path: artifact.tar.gz
