name: Build MG15 Vacuum Gauge Logger

on:
  workflow_dispatch:

jobs:

  build:
    name: Build MG15 Vacuum Gauge Logger
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    # - name: Install UPX
    #   uses: crazy-max/ghaction-upx@v2
    #   with:
    #     install-only: true

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Resolving dependencies...
      run: pip install -r requirements_mg15.txt pyinstaller

    - name: Building...
      run: pyinstaller mg15.spec

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: MG15
        path: dist/mg15/